services:
  frosttide_broker_account:
    image: mcr.microsoft.com/devcontainers/typescript-node:22
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=db
      - DB_USER=db
      - DB_PASSWORD=db
    ports:
      - 1042:80
    command: sleep infinity
    volumes:
      - ./:/workspace
  db:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    networks:
      - frosttide_broker_account_internal_network
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 1043:8080
    networks:
      - frosttide_broker_account_internal_network
volumes:
  db_data:
networks:
  kafka_external_network:
    external: true
    name: 'kafka_external'
  frosttide_broker_account_internal_network:
    external: false
    name: 'frosttide_broker_account_internal_network'
